on:
  push:
    branches:
    - $default-branch
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        IMAGE_NAME="snarky/gh-deploy"
        IMAGE_TAG="$(git describe --abbrev=0 --tags)"
        DOCKER_BUILDKIT=1 docker build \
          --build-arg "VERSION=${IMAGE_TAG}" \
          --tag "${IMAGE_NAME}:${IMAGE_TAG}" \
          .
