on:
  deployment:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "HELLO"
        env
        echo "HELM CHART VERSION: $(jq -r '.deployment.payload.helm_chart_version' "${GITHUB_EVENT_PATH}")"
