on:
  deployment:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/github-script@v4.0.2
      with:
        github-token: ${{secrets.GH_TOKEN}}
        script: |
          const result = await github.repos.createDeploymentStatus({
            "owner": "snarky",
            "repo": "gh-deploy",
            "deployment_id": "${{ github.event.deployment.id }}",
            "mediaType": {
              "previews": ["flash"],
            },
            "state": "in_progress",
          });
          
    - id: deploy 
      run: |
        echo "🚀 HELLO"
        echo "--"
        env
        echo "--"
        echo "HELM CHART VERSION: $(jq -r '.' "${GITHUB_EVENT_PATH}")"
        echo "--"
        echo "APP_NAME: HELLO"
        echo "APP_VERSION: 0.1.0"
        echo "HELM CHART VERSION: ${{ github.event.deployment.payload.helm_chart_version }}"
        echo "ENVIRONMENT: ${{ github.event.deployment.environment }}"
        sleep 30
        echo "Done!"
        exit 1
        
    # exit "$(shuf -i 0-1 -n 1)"

    - if: always()
      run: |
        echo "ALWAYS"
        echo "DEPLOY STATUS: ${{ job.steps.deploy.status }}"
    #- uses: actions/github-script@v4.0.2
    #  with:
    #    github-token: ${{secrets.GH_TOKEN}}
    #    script: |
    #      const result = await github.repos.createDeploymentStatus({
    #        "owner": "snarky",
    #        "repo": "gh-deploy",
    #        "deployment_id": "${{ github.event.deployment.id }}",
    #        "state": "failure",
    #      });
