on:
  deployment:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "HELLO"
        env
      env:
       TOTO: "${{fromJSON(github.event)}}"      
