on:
  push:
    branches:
    - next

name: Push

jobs:
  change:
    runs-on: ubuntu-latest
    outputs:
      app_ids: ${{ steps.filter_apps.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter_apps
      with:
        filters: .github/apps.yaml

  build:
    needs: [change]
    # Check if node_versions matrix is not empty to avoid error message:
    # "Error when evaluating 'strategy' for job '?'. (Line: ?, Col: ?): Matrix vector '?' does not contain any values"
    if: ${{ needs.change.outputs.app_ids != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        APP_ID: ${{ fromJson(needs.change.outputs.app_ids) }}
    steps:
    - run: |
        echo "APP_ID: ${{ matrix.APP_ID}}"
