on:
  workflow_run:
    workflows: ["Push", "Tag"]
    branches: [next]
    types: 
      - completed
      - requested
jobs:
  check-requirements:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "on.workflow_run"
